-- AlterTable
ALTER TABLE "Room" ALTER COLUMN "code" SET DEFAULT LPAD(FLOOR(RANDOM() * 100000)::text, 5, '0');

-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "storageUsed" INTEGER NOT NULL DEFAULT 0;
