name: ${COMPOSE_PROJECT_NAME:-sync-beats}
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    image: ghcr.io/smanikanta21/syncbeats-server:${IMAGE_TAG:-latest}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT:-4000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connection_limit=10&connect_timeout=15}
      # Auth
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      # Email
      AUTH_FROM_EMAIL: ${AUTH_FROM_EMAIL}
      UPDATES_FROM_EMAIL: ${UPDATES_FROM_EMAIL:-updates@syncbeats.app}
      RESEND_API_KEY: ${RESEND_API_KEY}
      # RapidAPI Configuration
      RAPID_API_KEY: ${RAPID_API_KEY:-}
      RAPID_API_KEYS: ${RAPID_API_KEYS:-}
    volumes:
      - uploads:/app/uploads
      - ./yt-dlp-cache:/root/.cache/yt-dlp

  frontend:
    image: ghcr.io/smanikanta21/syncbeats-frontend:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

  visualizer:
    image: ghcr.io/smanikanta21/syncbeats-db-visualizer:${IMAGE_TAG:-latest}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${STUDIO_PORT:-5555}:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}}
      AUTH_FROM_EMAIL: ${AUTH_FROM_EMAIL}
      UPDATES_FROM_EMAIL: ${UPDATES_FROM_EMAIL:-updates@syncbeats.app}
      RESEND_API_KEY: ${RESEND_API_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}


volumes:
  pgdata:
  uploads:

networks:
  default:
    enable_ipv6: true