import 'dotenv/config';
import prisma from '../src/db/prisma';
import { buildReleaseAnnouncementHtml } from '../src/auth/EmailTemplates';

async function sendEmail(to: string, subject: string, html: string): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  const authAddress = process.env.AUTH_FROM_EMAIL;
  const from = authAddress ? `SYNCBEATS <${authAddress}>` : authAddress;
  
  if (!apiKey || !from) {
    throw new Error('Email service is not configured. Set RESEND_API_KEY and AUTH_FROM_EMAIL.');
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ from, to: [to], subject, html }),
  });

  const rawBody = await response.text();
  if (!response.ok) {
    throw new Error(`Resend email send failed: ${rawBody}`);
  }

  console.info(`[Announcement] Email queued to ${to}.`);
}

const EXCLUDED_EMAILS = new Set([
  // First batch (51)
  "nibirnibir730@gmail.com",
  "aradulovic000@gmail.com",
  "aditya.karanje80555@gmail.com",
  "idukhin@yandex.com",
  "mjohnpaul567@gmail.com",
  "mmehtabkabir@gmail.com",
  "wfl2928341606@gmail.com",
  "balnasrikar@gmail.com",
  "asadkhan004112@gmail.com",
  "sharifkhan96909@gmail.com",
  "yasini.zahra2000@gmail.com",
  "indanaroopesh1999@gmail.com",
  "harshithak1415@gmail.com",
  "acricolor77@gmail.com",
  "mahmoud.samer2005@gmail.com",
  "iaamirahmed@gmail.com",
  "bmocevic2@gmail.com",
  "iliahesami4@gmail.com",
  "nyongesakevin871@gmail.com",
  "maxplayzz770@gmail.com",
  "nikmc20@gmail.com",
  "iosif625@gmail.com",
  "denisarebeca2021@gmail.com",
  "flohuaweii@gmail.com",
  "drmountaineous@gmail.com",
  "dimabobeico9@gmail.com",
  "robertgore028@gmail.com",
  "manarkalstana@gmail.com",
  "icancuz6@gmail.com",
  "adityakaranje09@gmail.com",
  "connorhoxworth90@gmail.com",
  "laujiny8701@gmail.com",
  "joshaviation763@gmail.com",
  "maverickman097@gmail.com",
  "dfacteromancerdf@gmail.com",
  "benjaminaco2015@gmail.com",
  "printprintmanila@gmail.com",
  "cyi91319@gmail.com",
  "oooo123456789xxxx@gmail.com",
  "rbakshay2@gmail.com",
  "nathanxitpow@gmail.com",
  "wmaxtsign@gmail.com",
  "kjfinest6@gmail.com",
  "liandlihah@gmail.com",
  "carterlane091@gmail.com",
  "arshitsharmacoc@gmail.com",
  "arshitsharma44@gmail.com",
  "corey.ray.robertson@gmail.com",
  "krzysztofworonko3@gmail.com",
  "siraparapu.mani2024@nst.rishihood.edu.in",
  "siraparapuabhinay21@gmail.com",

  // Second batch (148)
  "discordtestchat@gmail.com",
  "numanindikar@gmail.com",
  "yash85664@gmail.com",
  "patriots29fan@gmail.com",
  "mtahakamal246@gmail.com",
  "liammallon17@gmail.com",
  "pablo.lopez@dehonianospuente.es",
  "rishik3555@gmail.com",
  "jeremiahlongman85@gmail.com",
  "siposstanislav4@gmail.com",
  "raheemforgpt@gmail.com",
  "trecbret@gmail.com",
  "rrrreee20203@gmail.com",
  "teeewsrex@gmail.com",
  "frncssdeleon@gmail.com",
  "3552196844@qq.com",
  "mccarthjoe@gmail.com",
  "killi.kumar2024@nst.rishihood.edu.in",
  "tanmay.b@nst.rishihood.edu.in",
  "ivan.veshnii@gmail.com",
  "lilymaeyates06@gmail.com",
  "dreco.yuvienco@gmail.com",
  "doryayoub7@gmail.com",
  "3552195844@qq.com",
  "jureddisaipramodhnaidu123@gmail.com",
  "carlokarlo87@gmail.com",
  "rodarteluis454@gmail.com",
  "251721305@qq.com",
  "mohammeddowsa@gmail.com",
  "kingzanr23@gmail.com",
  "hemamdhar2108@gmail.com",
  "agiri9875@gmail.com",
  "aswinthprabhu94@gmail.com",
  "chakravarthihpnew189@gmail.com",
  "angelkummi123@gmail.com",
  "as79057482@gmail.com",
  "hasanmaruf0055@gmail.com",
  "teamsupertender@gmail.com",
  "chitangabi@gmail.com",
  "bysanisaikaushik@gmail.com",
  "mariuscurelusa.q@gmail.com",
  "25szymon25@gmail.com",
  "shree108.bhagat@gmail.com",
  "airdropy.25@gmail.com",
  "santhiapikachu@gmail.com",
  "miztanathan99@gmail.com",
  "dasalexander52@gmail.com",
  "reshwanthravi09@gmail.com",
  "ethan1landauer@gmail.com",
  "malkavtheclown@gmail.com",
  "emmanuel011719@gmail.com",
  "dshivesh5@gmail.com",
  "sachinmusicdirector@gmail.com",
  "ap2014337@gmail.com",
  "younessis72@gmail.com",
  "emmanuel28michael@gmail.com",
  "shaikmohammedwaseem7@gmail.com",
  "rakhich2605@gmail.com",
  "sakshamchaudhary1010@gmail.com",
  "kanishkachaudhary0608@gmail.com",
  "rehmanazeem942@gmail.com",
  "keerthiraj14036@gmail.com",
  "sankararaotentu5@gmail.com",
  "yadaminem@gmail.com",
  "soraya28056@gmail.com",
  "halimpaton@gmail.com",
  "jithupnz7@gmail.com",
  "ramyaarun1902@gmail.com",
  "251420331@qq.com",
  "wzx208323@qq.com",
  "a.navyasree2006@gmail.com",
  "pothalarajibabu123@gmail.com",
  "katariaakshath@gmail.com",
  "barneylewis@icloud.com",
  "rexy6090@gmail.com",
  "hemakanthbakka@gmail.com",
  "dreamspacedailyluxury@gmail.com",
  "thabisophumalo734@gmail.com",
  "alwinperson538@gmail.com",
  "ubithemba5@gmail.com",
  "mizunokokyu12345678910@gmail.com",
  "dikaelsaputra@students.untidar.ac.id",
  "gabrieleficchi@gmail.com",
  "lucaforster96@gmail.com",
  "bijoy2006mondall@gmail.com",
  "shubhajitdas354@gmail.com",
  "taleen.t.msalem@gmail.com",
  "itsme.rodayna@gmail.com",
  "villagesocialservice789@gmail.com",
  "sivasankarank75@gmail.com",
  "lyloulam1@gmail.com",
  "yadavtannu625@gmail.com",
  "s.prineiya@gmail.com",
  "sivelo9877@itquoted.com",
  "mananv1791@gmail.com",
  "petunia29mc@gmail.com",
  "maelclaverie2005@gmail.com",
  "siddharthag214@gmail.com",
  "seshamovie@gmail.com",
  "ishwor.dcine@gmail.com",
  "cristinasapkota7@gmail.com",
  "sapkotaishwor56@gmail.com",
  "kiquantentunnel@gmail.com",
  "gustavoabantuneds@gmail.com",
  "weltweit-daheim@web.de",
  "santosh8447466483@gmail.com",
  "razah43211@gmail.com",
  "hassan.kashif.pro@gmail.com",
  "gogoballs589@gmail.com",
  "quizora2026@gmail.com",
  "z1nevisuals@gmail.com",
  "mirceageorge086@gmail.com",
  "charanpaul2015189@gmail.com",
  "nehasinisingam@gmail.com",
  "pranavi0687@gmail.com",
  "gharsha1199@gmail.com",
  "romain.juvigny115@gmail.com",
  "bherwanijay22@gmail.com",
  "sunitasheoran13@gmail.com",
  "fiftyshadesofgrey696@gmail.com",
  "rawatarnav1909@gmail.com",
  "gaganagarwal830@gmail.com",
  "hiteshvaasan28@gmail.com",
  "badasbeast289@gmail.com",
  "full.inkorg@gmail.com",
  "casey.fyffe@gmail.com",
  "socialnahid@gmail.com",
  "businessinfo.nahid@gmail.com",
  "deathma984kgamingyt@gmail.com",
  "shadin15112001@gmail.com",
  "virendra46verma@gmail.com",
  "prabhatabhinandan9@gmail.com",
  "lalbinay10@gmail.com",
  "federico.sykes@gmail.com",
  "kushbhati007@gmail.com",
  "guzhihao16@gmail.com",
  "cena83631@gmail.com",
  "devyanshukumar052@gmail.com",
  "reyansh18110@gmail.com",
  "rajeshrajesh11405@gmail.com",
  "umerkakar07@gmail.com",
  "tanveershahshah999@gmail.com",
  "ehmedzaderehim249@gmail.com",
  "amirmirjalali65@gmail.com",
  "ankitsharma010205@gmail.com",

  // Third batch (69)
  "devanshisingh597@gmail.com",
  "lenkeejackcrypto@gmail.com",
  "sheikhabdullahzahid94@gmail.com",
  "kmanikumarreddy@live.com",
  "freedonationloot@gmail.com",
  "daskush8900@gmail.com",
  "naitikncccc@gmail.com",
  "mahdimnasrullah@gmail.com",
  "nasrullahmmahdi@gmail.com",
  "00mmehedihasan@gmail.com",
  "patdiyarishit604@gmail.com",
  "raselgamerff520@gmail.com",
  "samorjeetroy54@gmail.com",
  "raigul597@gmail.com",
  "mr7717268@gmail.com",
  "tohidul076@gmail.com",
  "adamnkabe@gmail.com",
  "arafattahsin34@gmail.com",
  "nathan.drake5562@gmail.com",
  "abh1i951931@gmail.com",
  "zicha15@seznam.cz",
  "abir.abiwar@gmail.com",
  "dart-unearth-awry@duck.com",
  "lauren.11.mckenzie+sync@gmail.com",
  "rahulbhoumik002@gmail.com",
  "fahimhasnatsoyad420@gmail.com",
  "mxnesha4118@gmail.com",
  "mailofravisharma@gmail.com",
  "ajijul89484@gmail.com",
  "parves0208@gmail.com",
  "newnew122123@gmail.com",
  "nahiyan.bd21@gmail.com",
  "abhi.businesscontact@gmail.com",
  "mcfox3140@gmail.com",
  "chikiig560@gmail.com",
  "pritomshikdar67@gmail.com",
  "nazirhos213@gmail.com",
  "shakibulislam989@gmail.com",
  "sharminmoon02@gmail.com",
  "samiramoushi04@gmail.com",
  "amirridoy31@gmail.com",
  "anashusseinb97@gmail.com",
  "naresh.balan99@gmail.com",
  "rakibul16.info@gmail.com",
  "keyurhirpara91@gmail.com",
  "mymoonlightsky03@gmail.com",
  "aiuseonly9997@gmail.com",
  "sarthakpatel806@gmail.com",
  "harisuchiindharmendra@gmail.com",
  "ahmedasifmahu1999@gmail.com",
  "sabbirrafi1997@gmail.com",
  "akibelahi123@gmail.com",
  "tehjibkayser2005@gmail.com",
  "mahfuzshadhin7@gmail.com",
  "mriglinsingh20@gmail.com",
  "runescapejaynot@gmail.com",
  "trendsetter5710@gmail.com",
  "alixmorningstar14@gmail.com",
  "kunjadiyaherin@gmail.com",
  "afifatasnim307@gmail.com",
  "mhnmubasshir@gmail.com",
  "salman.suad99@gmail.com",
  "shahana.parvin98765@gmail.com",
  "siraparapusirisha2@gmail.com",
  "siraparapupolinaidu183@gmail.com",
  "wcc17.tuc@gmail.com",
  "williamchristiancandra@gmail.com",
  "armanahmedjemi85@gmail.com",
  "mahirshahariyar777@gmail.com"
].map(email => email.toLowerCase().trim()));

async function main() {
  console.log("Fetching users from database...");
  const allUsers = await prisma.user.findMany({
    select: { email: true, name: true },
  });

  const users = allUsers.filter(user => !EXCLUDED_EMAILS.has(user.email.toLowerCase().trim()));

  console.log(`Found ${allUsers.length} total users in DB. Filtered to ${users.length} remaining users to send announcements...`);

  const title = "Introducing Streamlined Sync: Share and Listen in Real-Time";

  for (const user of users) {
    try {
      const html = buildReleaseAnnouncementHtml(user.name);
      await sendEmail(user.email, title, html);
      // Paced to send exactly one email every two seconds
      await new Promise(r => setTimeout(r, 2000));
    } catch (err) {
      console.error(`Failed to send to ${user.email}:`, err);
    }
  }

  console.log("Done!");
  process.exit(0);
}

main().catch(console.error);
